### ISSUE TITLE
Error handler for some questions

### ISSUE THREAD

**Issue by MoafaqJamal** [MHSEA/HotelReception#3]
Hi guys, I just discovered when typing what or where and then a word which is not part of our class types. For examples: "where is that" "what is that" or "what dsfsdfsdfsdf" then an error message appear instead of the "sorry I didn't understand" message:

Exception in thread "AWT-EventQueue-0" subjectcounter = 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at Reception.Reasoner.generateAnswer(Reasoner.java:572)
	at Reception.MainReception.generateanswer(MainReception.java:262)
	at Reception.MainReception.questionasked(MainReception.java:256)
	at Reception.MainReception$6.actionPerformed(MainReception.java:221)
	at javax.swing.JTextField.fireActionPerformed(JTextField.java:508)
	at javax.swing.JTextField.postActionEvent(JTextField.java:721)
	at javax.swing.JTextField$NotifyAction.actionPerformed(JTextField.java:836)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I tried to modify the code by adding else statement to the IFs but I couldn't fix it. It could be from other part of the code which I'm not sure about. Can you please investigate?

Thanks

**Comment by MHSEA** [comment]
Well in regards to this situation, I believe you have tried [where is that] alone which indeed the response would be nothing! These are part of the continues conversations for instance:

*I am looking for pool.*
*Where is it?*

Of course, in a normal conversation you can not just say *where is it?* to start.

In regards to *What is that*, we do not have such a thing like I am looking for club and then what is that?
It doesn't sound right :smiley:

At the end we can implement something to show the **sorry I didn't understand that....** message for that type of questions which are follow up questions. Other than that it would be the case of developing continues conversations with more steps and stages.

For instance:
*where is that?*
*Sorry i didnt undrestand that, what are you looking for ?*
*pool*
*pool is located ....*

I will try to implement somthing and I will keep you guys update. :+1:
